const [aset,setAset] = useState([
    //aset penangkar
    {id : 'benih1', 
    benihID : 'benih1', 
    manggaID : '', 
    namaPengirim : 'penangkarAgus', 
    namaPenerima : '', 
    kuantitasBenihKg : 10, 
    hargaBenihPerKg : 0, 
    hargaBenihTotal : 0, 
    kuantitasManggaKg : 0, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 0, 
    varietasBenih : 'Mangga arum manis', 
    umurBenih : 2, 
    pupuk : '', 
    tanggalTanam : 1648757753, 
    lokasiLahan : '', 
    ukuran : '', 
    pestisida : '', 
    kadarAir : 0, 
    perlakuan : '', 
    produktivitas : '', 
    tanggalPanen : 0, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : '', 
    txID1 : '', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : true, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    {id : 'benih2', 
    benihID : 'benih2', 
    manggaID : '', 
    namaPengirim : 'penangkarAgus', 
    namaPenerima : '', 
    kuantitasBenihKg : 15, 
    hargaBenihPerKg : 0, 
    hargaBenihTotal : 0, 
    kuantitasManggaKg : 0, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 0, 
    varietasBenih : 'Benih B', 
    umurBenih : 6, 
    pupuk : '', 
    tanggalTanam : 1648054793, 
    lokasiLahan : '', 
    ukuran : '', 
    pestisida : '', 
    kadarAir : 0, 
    perlakuan : '', 
    produktivitas : '', 
    tanggalPanen : 0, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : '', 
    txID1 : '', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : true, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},    
    
    //trx penangkar -> petani
    {id : 'trxPenangkarkePetani1', 
    benihID : 'benih1', 
    manggaID : '', 
    namaPengirim : 'penangkarAgus', 
    namaPenerima : 'petani1', 
    kuantitasBenihKg : 5, 
    hargaBenihPerKg : 10000, 
    hargaBenihTotal : 50000, 
    kuantitasManggaKg : 0, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 1664438875, 
    varietasBenih : 'Mangga arum manis', 
    umurBenih : 3, 
    pupuk : '', 
    tanggalTanam : 0, 
    lokasiLahan : '', 
    ukuran : '', 
    pestisida : '', 
    kadarAir : 0, 
    perlakuan : '', 
    produktivitas : '', 
    tanggalPanen : 0, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : ['Tunai', 'Transfer'], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    {id : 'trxPenangkarkePetani2', 
    benihID : 'benih2', 
    manggaID : '', 
    namaPengirim : 'penangkarAgus', 
    namaPenerima : 'petani1', 
    kuantitasBenihKg : 7, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 0, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 1664434847, 
    varietasBenih : 'Mangga Alpukat', 
    umurBenih : 3, 
    pupuk : '', 
    tanggalTanam : 0, 
    lokasiLahan : '', 
    ukuran : '', 
    pestisida : '', 
    kadarAir : 0, 
    perlakuan : '', 
    produktivitas : '', 
    tanggalPanen : 0, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : ['Tunai'], 
    txID1 : 'trxPenangkarkePetani2', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : true, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    {id : 'trxPenangkarkePetani3', 
    benihID : 'benih2', 
    manggaID : '', 
    namaPengirim : 'penangkarAgus', 
    namaPenerima : 'petani2', 
    kuantitasBenihKg : 14, 
    hargaBenihPerKg : 5000, 
    hargaBenihTotal : 70000, 
    kuantitasManggaKg : 0, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 1645668000, 
    varietasBenih : 'Mangga alpukat', 
    umurBenih : 6, 
    pupuk : '', 
    tanggalTanam : 0, 
    lokasiLahan : '', 
    ukuran : '', 
    pestisida : '', 
    kadarAir : 0, 
    perlakuan : '', 
    produktivitas : '', 
    tanggalPanen : 0, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : ['Transfer'], 
    txID1 : 'trxPenangkarkePetani3', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : true, 
    rejectReason : 'Harga tidak sesuai'},

    //aset petani == Transaksi Masuk  && isConfirmed true

    //data sudah tanam benih
    {id : 'asetTanamBenih1', 
    benihID : 'benih1', 
    manggaID : 'asetTanamBenih1', 
    namaPengirim : 'petani1', 
    namaPenerima : '', 
    kuantitasBenihKg : 5, 
    hargaBenihPerKg : 10000, 
    hargaBenihTotal : 50000, 
    kuantitasManggaKg : 0, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 1657589335, 
    varietasBenih : 'Benih AA', 
    umurBenih : 3, 
    pupuk : 'pupuk Kompos', 
    tanggalTanam : 1657589210, 
    lokasiLahan : '', 
    ukuran : '', 
    pestisida : '', 
    kadarAir : 0, 
    perlakuan : '', 
    produktivitas : '', 
    tanggalPanen : 0, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : [], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : true, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : true,
    rejectReason : ''},
    //data sudah panen
    {id : 'asetTanamBenih2', 
    benihID : 'benih2', 
    manggaID : 'asetTanamBenih2', 
    namaPengirim : 'petani1', 
    namaPenerima : '', 
    kuantitasBenihKg : 7, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 10, 
    hargaManggaPerKg : 0, 
    hargaManggaTotal : 0, 
    tanggalTransaksi : 1641967200, 
    varietasBenih : 'Benih AB', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1657589200, 
    lokasiLahan : '', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1657589335, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : [], 
    txID1 : 'trxPenangkarkePetani3', 
    txID2 : '', 
    txID3 : '', 
    txID4 : '', 
    isAsset : true, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    // trx petani -> pengumpul
    {id : 'trxPetanikePengumpul1', 
    benihID : 'benih1', 
    manggaID : 'asetTanamBenih1', 
    namaPengirim : 'petani1', 
    namaPenerima : 'pengumpul1', 
    kuantitasBenihKg : 3, 
    hargaBenihPerKg : 10000, 
    hargaBenihTotal : 50000, 
    kuantitasManggaKg : 10, 
    hargaManggaPerKg : 10000, 
    hargaManggaTotal : 100000, 
    tanggalTransaksi : 1657589335, 
    varietasBenih : 'Benih AA', 
    umurBenih : 6, 
    pupuk : 'pupuk ABC', 
    tanggalTanam : 1647589335, 
    lokasiLahan : 'Bogor', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1657589335, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung', 'Transfer via Bank'], 
    txID1 : 'trxPenangkarkePetani3', 
    txID2 : 'trxPetanikePengumpul1', 
    txID3 : '', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    {id : 'trxPetanikePengumpul3', 
    benihID : 'benih2', 
    manggaID : 'asetTanamBenih2', 
    namaPengirim : 'petani1', 
    namaPenerima : 'pengumpul1', 
    kuantitasBenihKg : 7, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 10, 
    hargaManggaPerKg : 15000, 
    hargaManggaTotal : 150000, 
    tanggalTransaksi : 1647585225, 
    varietasBenih : 'Benih AB', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1647580225, 
    lokasiLahan : 'Bogor', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1647585335, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung'], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : 'trxPetanikePengumpul3', 
    txID3 : '', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : true, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    {id : 'trxPetanikePengumpul2', 
    benihID : 'benih1', 
    manggaID : 'asetTanamBenih2', 
    namaPengirim : 'petani1', 
    namaPenerima : 'pengumpul123', 
    kuantitasBenihKg : 2, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 2, 
    hargaManggaPerKg : 15000, 
    hargaManggaTotal : 30000, 
    tanggalTransaksi : 1651967400, 
    varietasBenih : 'Benih AC', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1657589200, 
    lokasiLahan : 'Bogor', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1657589335, 
    tanggalMasuk : 0, 
    teknikSorting : '', 
    metodePengemasan : '', 
    pengangkutan : '', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung'], 
    txID1 : 'trxPenangkarkePetani2', 
    txID2 : 'trxPetanikePengumpul2', 
    txID3 : '', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : true, 
    rejectReason : 'Kuantitas Kurang'},

    //aset pengumpul == trx masuk && isConfirmed true
    
    //trx pengumpul -> pedagang
    {id : 'trxPengumpulkePedagang1', 
    benihID : 'benih1', 
    manggaID : 'asetTanamBenih2', 
    namaPengirim : 'pengumpul1', 
    namaPenerima : 'pedagang1', 
    kuantitasBenihKg : 5, 
    hargaBenihPerKg : 10000, 
    hargaBenihTotal : 50000, 
    kuantitasManggaKg : 10, 
    hargaManggaPerKg : 15000, 
    hargaManggaTotal : 150000, 
    tanggalTransaksi : 1647585225, 
    varietasBenih : 'Benih AB', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1647580225, 
    lokasiLahan : '', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1647585335, 
    tanggalMasuk : 0, 
    teknikSorting : 'AAA', 
    metodePengemasan : 'BBB', 
    pengangkutan : 'CCCC', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung'], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : 'trxPetanikePengumpul3', 
    txID3 : 'trxPengumpulkePedagang1', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},
    
    {id : 'trxPengumpulkePedagang2', 
    benihID : 'benih2', 
    manggaID : 'asetTanamBenih2', 
    namaPengirim : 'pengumpul1', 
    namaPenerima : 'pedagang1', 
    kuantitasBenihKg : 7, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 9, 
    hargaManggaPerKg : 18000, 
    hargaManggaTotal : 162000, 
    tanggalTransaksi : 1677985325, 
    varietasBenih : 'Benih AB', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1647580225, 
    lokasiLahan : 'Bandung', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1647585335, 
    tanggalMasuk : 0, 
    teknikSorting : 'AAA', 
    metodePengemasan : 'BBB', 
    pengangkutan : 'CCCC', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung'], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : 'trxPetanikePengumpul2', 
    txID3 : 'trxPengumpulkePedagang2', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : true, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},

    {id : 'trxPengumpulkePedagang3', 
    benihID : 'benih2', 
    manggaID : 'asetTanamBenih2', 
    namaPengirim : 'pengumpul1', 
    namaPenerima : 'pedagang1', 
    kuantitasBenihKg : 7, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 1, 
    hargaManggaPerKg : 5000, 
    hargaManggaTotal : 5000, 
    tanggalTransaksi : 1667589525, 
    varietasBenih : 'Benih AB', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1647580225, 
    lokasiLahan : 'Bandung', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1647585335, 
    tanggalMasuk : 0, 
    teknikSorting : 'AAA', 
    metodePengemasan : 'BBB', 
    pengangkutan : 'CCCC', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung'], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : 'trxPetanikePengumpul1', 
    txID3 : 'trxPengumpulkePedagang3', 
    txID4 : '', 
    isAsset : false, 
    isConfirmed : false, 
    isEmpty : false, 
    isRejected : true, 
    rejectReason : 'Harga terlalu murah'},

    //aset pedagang === trx masuk && isConfirmed true

    //trx pedagang
    {id : 'trxPedagang1', 
    benihID : 'benih1', 
    manggaID : 'asetTanamBenih7', 
    namaPengirim : 'pedagang1', 
    namaPenerima : '-', 
    kuantitasBenihKg : 7, 
    hargaBenihPerKg : 9000, 
    hargaBenihTotal : 63000, 
    kuantitasManggaKg : 9, 
    hargaManggaPerKg : 20000, 
    hargaManggaTotal : 180000, 
    tanggalTransaksi : 1677985325, 
    varietasBenih : 'Benih AB', 
    umurBenih : 3, 
    pupuk : 'pupuk AA', 
    tanggalTanam : 1647580225, 
    lokasiLahan : 'Bandung', 
    ukuran : 'Besar', 
    pestisida : 'Lorem ipsum', 
    kadarAir : 90, 
    perlakuan : 'Shading net', 
    produktivitas : 'lorem ipsum', 
    tanggalPanen : 1647585335, 
    tanggalMasuk : 0, 
    teknikSorting : 'AAA', 
    metodePengemasan : 'BBB', 
    pengangkutan : 'CCCC', 
    pembeli : '', 
    caraPembayaran : ['Bayar Langsung'], 
    txID1 : 'trxPenangkarkePetani1', 
    txID2 : 'trxPetanikePengumpul2', 
    txID3 : 'trxPengumpulkePedagang2', 
    txID4 : 'trxPedagang1', 
    isAsset : false, 
    isConfirmed : true, 
    isEmpty : false, 
    isRejected : false, 
    isPanen : false,
    rejectReason : ''},
])